name: odometer_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  connectivity_plus: ^6.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_ringtone_player: ^4.0.0+3
  flutter_smartcar_auth: ^2.0.0
  http: ^1.2.2
  intl: ^0.20.1
  path: ^1.9.0
  path_provider: ^2.1.5
  screen_brightness: ^2.0.0+2
  share_plus: ^10.1.2
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  assets:
    - assets/database_create.txt
    - assets/icons/drivex_icon.png
  uses-material-design: true
